// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './dbTypes';

// Allow environment overrides for testing/staging vs production while keeping safe defaults.
const env = (import.meta as unknown as { env?: Record<string, string | undefined> }).env;

const SUPABASE_URL = env?.VITE_SUPABASE_URL ?? "https://thxrxacsrwtadvvdwken.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = env?.VITE_SUPABASE_PUBLISHABLE_KEY ?? "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRoeHJ4YWNzcnd0YWR2dmR3a2VuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzMTQwMjgsImV4cCI6MjA3Nzg5MDAyOH0._yxKbMzL2DPwkOrManeodLIrmHurBxwI1uTiyS-U-XM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Safari-compatible storage adapter
const safariStorage = {
  getItem: (key: string) => {
    try {
      return localStorage.getItem(key);
    } catch (e) {
      console.warn('Storage access failed:', e);
      return null;
    }
  },
  setItem: (key: string, value: string) => {
    try {
      localStorage.setItem(key, value);
    } catch (e) {
      console.warn('Storage write failed:', e);
    }
  },
  removeItem: (key: string) => {
    try {
      localStorage.removeItem(key);
    } catch (e) {
      console.warn('Storage remove failed:', e);
    }
  }
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: safariStorage as any,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
    // Safari-specific: Add storage key prefix
    storageKey: 'citylifes-auth-token',
  },
  global: {
    headers: {
      'X-Client-Info': 'citylifes-web',
    },
  },
  db: {
    schema: 'public',
  },
  // Improve reliability for all browsers
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
});